console.log("Swap Two Variable Using Third Variable");
var sweety = "Sweety";
var cutie = "Cutie";
console.log("Before Swaping");
console.log("Sweety :", sweety, "Cutie :", cutie);
console.log("After Swaping");
var temp = sweety;
sweety = cutie;
cutie = temp;
console.log("Sweety :", sweety, "Cutie :", cutie);
console.log("---------------------------------------------------------------------------");
console.log("Swap Three Variable Using Third Variable");
var num1 = 100;
var num2 = 200;
var num3 = 300;
console.log("Before Swaping");
console.log("Num 1 :", num1, "Num 2 :", num2, "Num 3 :", num3);
console.log("After Swaping");
var temp = num1;
num1 = num2;
num2 = num3;
num3 = temp;
console.log("Num 1 :",num1, "Num 2 :", num2, "Num 3 :", num3);
